import {
  Workflow,
  KnowledgeBase,
  Prompt,
  Deployment,
  WorkflowRun,
  MonitoringStats,
  MarketplaceItem,
  Team,
  User,
} from "@/types";

export const mockUser: User = {
  id: "user-1",
  email: "alex@buildstream.dev",
  name: "Alex Chen",
  avatar_url: null,
  created_at: "2024-01-01T00:00:00Z",
};

export const mockTeam: Team = {
  id: "team-1",
  name: "BuildStream Team",
  owner_id: "user-1",
  members: [
    {
      user_id: "user-1",
      name: "Alex Chen",
      email: "alex@buildstream.dev",
      role: "owner",
      avatar_url: null,
      joined_at: "2024-01-01T00:00:00Z",
    },
    {
      user_id: "user-2",
      name: "Jordan Lee",
      email: "jordan@buildstream.dev",
      role: "admin",
      avatar_url: null,
      joined_at: "2024-01-05T00:00:00Z",
    },
    {
      user_id: "user-3",
      name: "Sam Patel",
      email: "sam@buildstream.dev",
      role: "editor",
      avatar_url: null,
      joined_at: "2024-01-10T00:00:00Z",
    },
    {
      user_id: "user-4",
      name: "Taylor Kim",
      email: "taylor@buildstream.dev",
      role: "viewer",
      avatar_url: null,
      joined_at: "2024-02-01T00:00:00Z",
    },
  ],
  created_at: "2024-01-01T00:00:00Z",
};

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Customer Support Bot",
    description: "An AI chatbot that handles customer inquiries using a knowledge base of support docs.",
    app_type: "chatbot",
    blocks: [
      {
        id: "block-input",
        type: "input",
        label: "User Message",
        config: {
          input: {
            fields: [
              { id: "f1", name: "message", type: "text", label: "Message", required: true },
            ],
          },
        },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 50 },
      },
      {
        id: "block-kb",
        type: "knowledge_base",
        label: "Search Support Docs",
        config: {
          knowledge_base: {
            store_id: "kb-1",
            query_variable: "message",
            top_k: 5,
            similarity_threshold: 0.7,
          },
        },
        error_config: { retry_count: 2, retry_delay_ms: 1000, fallback_block_id: null, notify_on_error: true },
        position: { x: 250, y: 200 },
      },
      {
        id: "block-template",
        type: "template",
        label: "Build Prompt",
        config: {
          template: {
            template:
              "You are a helpful customer support agent. Use the following context to answer the question.\n\nContext:\n{{context}}\n\nQuestion: {{message}}\n\nProvide a helpful, concise answer.",
            variables: ["context", "message"],
          },
        },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 350 },
      },
      {
        id: "block-llm",
        type: "llm",
        label: "Generate Response",
        config: {
          llm: {
            model: "gpt-4",
            temperature: 0.7,
            max_tokens: 500,
            system_prompt: "You are a helpful customer support assistant.",
            user_prompt: "{{prompt}}",
            stream: true,
          },
        },
        error_config: { retry_count: 3, retry_delay_ms: 2000, fallback_block_id: null, notify_on_error: true },
        position: { x: 250, y: 500 },
      },
      {
        id: "block-output",
        type: "output",
        label: "Response",
        config: {
          output: { format: "text", template: "{{response}}" },
        },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 650 },
      },
    ],
    edges: [
      { id: "e1", source: "block-input", target: "block-kb", source_handle: null, target_handle: null },
      { id: "e2", source: "block-kb", target: "block-template", source_handle: null, target_handle: null },
      { id: "e3", source: "block-template", target: "block-llm", source_handle: null, target_handle: null },
      { id: "e4", source: "block-llm", target: "block-output", source_handle: null, target_handle: null },
    ],
    variables: [
      { id: "v1", name: "message", type: "string", default_value: "", description: "User input message", scope: "global" },
      { id: "v2", name: "context", type: "string", default_value: "", description: "Retrieved context from KB", scope: "local" },
    ],
    created_by: "user-1",
    team_id: "team-1",
    is_public: false,
    version: 3,
    status: "published",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-02-20T14:30:00Z",
  },
  {
    id: "wf-2",
    name: "Blog Post Generator",
    description: "Generate SEO-optimized blog posts from topic and keywords.",
    app_type: "text_generator",
    blocks: [
      {
        id: "block-input-2",
        type: "input",
        label: "Blog Input",
        config: {
          input: {
            fields: [
              { id: "f1", name: "topic", type: "text", label: "Topic", required: true },
              { id: "f2", name: "keywords", type: "text", label: "Keywords", required: true },
              { id: "f3", name: "tone", type: "select", label: "Tone", required: true, options: ["Professional", "Casual", "Academic"] },
            ],
          },
        },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 50 },
      },
      {
        id: "block-llm-outline",
        type: "llm",
        label: "Generate Outline",
        config: {
          llm: {
            model: "gpt-4",
            temperature: 0.8,
            max_tokens: 1000,
            system_prompt: "You are an expert content strategist.",
            user_prompt: "Create a detailed blog post outline for: {{topic}}. Keywords: {{keywords}}. Tone: {{tone}}.",
            stream: false,
          },
        },
        error_config: { retry_count: 2, retry_delay_ms: 1000, fallback_block_id: null, notify_on_error: true },
        position: { x: 250, y: 200 },
      },
      {
        id: "block-llm-write",
        type: "llm",
        label: "Write Blog Post",
        config: {
          llm: {
            model: "gpt-4",
            temperature: 0.7,
            max_tokens: 3000,
            system_prompt: "You are a skilled blog writer.",
            user_prompt: "Write a full blog post based on this outline:\n{{outline}}\n\nKeywords to include: {{keywords}}\nTone: {{tone}}",
            stream: true,
          },
        },
        error_config: { retry_count: 2, retry_delay_ms: 2000, fallback_block_id: null, notify_on_error: true },
        position: { x: 250, y: 400 },
      },
      {
        id: "block-output-2",
        type: "output",
        label: "Blog Post Output",
        config: {
          output: { format: "markdown", template: "{{blog_post}}" },
        },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 600 },
      },
    ],
    edges: [
      { id: "e1", source: "block-input-2", target: "block-llm-outline", source_handle: null, target_handle: null },
      { id: "e2", source: "block-llm-outline", target: "block-llm-write", source_handle: null, target_handle: null },
      { id: "e3", source: "block-llm-write", target: "block-output-2", source_handle: null, target_handle: null },
    ],
    variables: [
      { id: "v1", name: "topic", type: "string", default_value: "", description: "Blog topic", scope: "global" },
      { id: "v2", name: "keywords", type: "string", default_value: "", description: "SEO keywords", scope: "global" },
      { id: "v3", name: "tone", type: "string", default_value: "Professional", description: "Writing tone", scope: "global" },
    ],
    created_by: "user-1",
    team_id: "team-1",
    is_public: true,
    version: 2,
    status: "published",
    created_at: "2024-02-01T09:00:00Z",
    updated_at: "2024-02-25T11:00:00Z",
  },
  {
    id: "wf-3",
    name: "Data Research Agent",
    description: "An autonomous agent that researches topics by searching the web and synthesizing findings.",
    app_type: "agent",
    blocks: [
      {
        id: "block-in3",
        type: "input",
        label: "Research Query",
        config: {
          input: {
            fields: [{ id: "f1", name: "query", type: "text", label: "Research Question", required: true }],
          },
        },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 50 },
      },
      {
        id: "block-http3",
        type: "http_request",
        label: "Web Search",
        config: {
          http_request: {
            method: "GET",
            url: "https://api.search.example.com/search?q={{query}}",
            headers: { Authorization: "Bearer {{api_key}}" },
            body: "",
            timeout_ms: 10000,
          },
        },
        error_config: { retry_count: 3, retry_delay_ms: 2000, fallback_block_id: null, notify_on_error: true },
        position: { x: 250, y: 200 },
      },
      {
        id: "block-code3",
        type: "code",
        label: "Parse Results",
        config: {
          code: {
            language: "javascript",
            code: "const results = JSON.parse(input.search_results);\nreturn results.items.slice(0, 5).map(item => ({\n  title: item.title,\n  snippet: item.snippet,\n  url: item.url\n}));",
            timeout_ms: 5000,
          },
        },
        error_config: { retry_count: 1, retry_delay_ms: 500, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 350 },
      },
      {
        id: "block-llm3",
        type: "llm",
        label: "Synthesize Research",
        config: {
          llm: {
            model: "gpt-4",
            temperature: 0.5,
            max_tokens: 2000,
            system_prompt: "You are a thorough research assistant. Synthesize information from multiple sources into a comprehensive report.",
            user_prompt: "Research question: {{query}}\n\nSearch results:\n{{parsed_results}}\n\nProvide a comprehensive research report.",
            stream: true,
          },
        },
        error_config: { retry_count: 2, retry_delay_ms: 2000, fallback_block_id: null, notify_on_error: true },
        position: { x: 250, y: 500 },
      },
      {
        id: "block-out3",
        type: "output",
        label: "Research Report",
        config: { output: { format: "markdown", template: "{{report}}" } },
        error_config: { retry_count: 0, retry_delay_ms: 0, fallback_block_id: null, notify_on_error: false },
        position: { x: 250, y: 650 },
      },
    ],
    edges: [
      { id: "e1", source: "block-in3", target: "block-http3", source_handle: null, target_handle: null },
      { id: "e2", source: "block-http3", target: "block-code3", source_handle: null, target_handle: null },
      { id: "e3", source: "block-code3", target: "block-llm3", source_handle: null, target_handle: null },
      { id: "e4", source: "block-llm3", target: "block-out3", source_handle: null, target_handle: null },
    ],
    variables: [
      { id: "v1", name: "query", type: "string", default_value: "", description: "Research question", scope: "global" },
    ],
    created_by: "user-1",
    team_id: "team-1",
    is_public: false,
    version: 1,
    status: "draft",
    created_at: "2024-03-01T08:00:00Z",
    updated_at: "2024-03-01T08:00:00Z",
  },
];

export const mockKnowledgeBases: KnowledgeBase[] = [
  {
    id: "kb-1",
    name: "Support Documentation",
    description: "Customer support knowledge base with product docs, FAQs, and troubleshooting guides.",
    document_count: 24,
    total_chunks: 1456,
    embedding_model: "text-embedding-3-small",
    status: "ready",
    created_by: "user-1",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-02-15T14:00:00Z",
  },
  {
    id: "kb-2",
    name: "Product Specifications",
    description: "Technical specifications and feature documentation for all products.",
    document_count: 12,
    total_chunks: 834,
    embedding_model: "text-embedding-3-small",
    status: "ready",
    created_by: "user-1",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-02-10T09:00:00Z",
  },
  {
    id: "kb-3",
    name: "Training Materials",
    description: "Internal training documents and onboarding materials.",
    document_count: 8,
    total_chunks: 0,
    embedding_model: "text-embedding-3-small",
    status: "processing",
    created_by: "user-2",
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
  },
];

export const mockPrompts: Prompt[] = [
  {
    id: "prompt-1",
    name: "Customer Support System Prompt",
    description: "System prompt for the customer support chatbot",
    content:
      "You are a helpful customer support agent for {{company_name}}. You have access to the following context from our knowledge base:\n\n{{context}}\n\nGuidelines:\n- Be friendly and professional\n- If you don't know the answer, say so and offer to escalate\n- Always provide actionable solutions\n- Reference specific documentation when possible",
    variables: ["company_name", "context"],
    version: 3,
    versions: [
      { id: "pv-1", prompt_id: "prompt-1", content: "You are a support agent.", version: 1, created_at: "2024-01-15T10:00:00Z", notes: "Initial version" },
      { id: "pv-2", prompt_id: "prompt-1", content: "You are a helpful support agent for {{company_name}}.", version: 2, created_at: "2024-01-20T10:00:00Z", notes: "Added company name variable" },
      {
        id: "pv-3",
        prompt_id: "prompt-1",
        content:
          "You are a helpful customer support agent for {{company_name}}. You have access to the following context from our knowledge base:\n\n{{context}}\n\nGuidelines:\n- Be friendly and professional\n- If you don't know the answer, say so and offer to escalate\n- Always provide actionable solutions\n- Reference specific documentation when possible",
        version: 3,
        created_at: "2024-02-01T10:00:00Z",
        notes: "Added context and guidelines",
      },
    ],
    ab_tests: [
      {
        id: "ab-1",
        prompt_id: "prompt-1",
        name: "Friendly vs Formal tone",
        variant_a: "You are a friendly, casual customer support agent...",
        variant_b: "You are a professional, formal customer support agent...",
        traffic_split: 50,
        status: "running",
        results: { variant_a_runs: 234, variant_b_runs: 228, variant_a_avg_score: 4.2, variant_b_avg_score: 3.8 },
        created_at: "2024-02-15T10:00:00Z",
      },
    ],
    created_by: "user-1",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "prompt-2",
    name: "Blog Writer Prompt",
    description: "Prompt for generating blog posts",
    content:
      "Write a comprehensive blog post about {{topic}}.\n\nKeywords to include: {{keywords}}\nTarget audience: {{audience}}\nTone: {{tone}}\nWord count: {{word_count}}\n\nStructure the post with:\n1. An engaging introduction\n2. Clear headings and subheadings\n3. Practical examples\n4. A compelling conclusion with call-to-action",
    variables: ["topic", "keywords", "audience", "tone", "word_count"],
    version: 2,
    versions: [
      { id: "pv-4", prompt_id: "prompt-2", content: "Write a blog post about {{topic}}.", version: 1, created_at: "2024-02-01T09:00:00Z", notes: "Initial version" },
      {
        id: "pv-5",
        prompt_id: "prompt-2",
        content:
          "Write a comprehensive blog post about {{topic}}.\n\nKeywords to include: {{keywords}}\nTarget audience: {{audience}}\nTone: {{tone}}\nWord count: {{word_count}}",
        version: 2,
        created_at: "2024-02-10T09:00:00Z",
        notes: "Added structured output",
      },
    ],
    ab_tests: [],
    created_by: "user-1",
    created_at: "2024-02-01T09:00:00Z",
    updated_at: "2024-02-10T09:00:00Z",
  },
];

export const mockDeployments: Deployment[] = [
  {
    id: "dep-1",
    workflow_id: "wf-1",
    workflow_name: "Customer Support Bot",
    target: "widget",
    url: "https://buildstream.dev/widget/dep-1",
    api_key: "bs_live_abc123def456",
    status: "active",
    config: {
      widget: {
        theme: "light",
        position: "bottom-right",
        title: "Support Assistant",
        welcome_message: "Hi! How can I help you today?",
        primary_color: "#6366f1",
      },
    },
    created_at: "2024-02-20T14:30:00Z",
    updated_at: "2024-02-20T14:30:00Z",
  },
  {
    id: "dep-2",
    workflow_id: "wf-1",
    workflow_name: "Customer Support Bot",
    target: "api",
    url: "https://api.buildstream.dev/v1/workflows/wf-1/run",
    api_key: "bs_live_xyz789ghi012",
    status: "active",
    config: {
      api: {
        rate_limit: 100,
        auth_required: true,
        cors_origins: ["https://example.com"],
      },
    },
    created_at: "2024-02-21T10:00:00Z",
    updated_at: "2024-02-21T10:00:00Z",
  },
  {
    id: "dep-3",
    workflow_id: "wf-2",
    workflow_name: "Blog Post Generator",
    target: "webapp",
    url: "https://buildstream.dev/app/blog-generator",
    api_key: "bs_live_mno345pqr678",
    status: "active",
    config: {
      webapp: {
        title: "AI Blog Post Generator",
        description: "Generate SEO-optimized blog posts in seconds",
        theme: "light",
        custom_domain: null,
      },
    },
    created_at: "2024-02-25T11:00:00Z",
    updated_at: "2024-02-25T11:00:00Z",
  },
];

export const mockRuns: WorkflowRun[] = [
  {
    id: "run-1",
    workflow_id: "wf-1",
    workflow_name: "Customer Support Bot",
    status: "success",
    started_at: "2024-03-15T10:30:00Z",
    completed_at: "2024-03-15T10:30:03Z",
    duration_ms: 2840,
    token_usage: { prompt_tokens: 450, completion_tokens: 180, total_tokens: 630 },
    input: { message: "How do I reset my password?" },
    output: { response: "To reset your password, go to Settings > Account > Change Password..." },
    error: null,
    block_runs: [
      { id: "br-1", block_id: "block-input", block_type: "input", block_label: "User Message", status: "success", started_at: "2024-03-15T10:30:00Z", completed_at: "2024-03-15T10:30:00Z", duration_ms: 5, input: {}, output: { message: "How do I reset my password?" }, error: null, retry_count: 0 },
      { id: "br-2", block_id: "block-kb", block_type: "knowledge_base", block_label: "Search Support Docs", status: "success", started_at: "2024-03-15T10:30:00Z", completed_at: "2024-03-15T10:30:01Z", duration_ms: 680, input: { query: "How do I reset my password?" }, output: { context: "Password reset instructions..." }, error: null, retry_count: 0 },
      { id: "br-3", block_id: "block-template", block_type: "template", block_label: "Build Prompt", status: "success", started_at: "2024-03-15T10:30:01Z", completed_at: "2024-03-15T10:30:01Z", duration_ms: 2, input: {}, output: { prompt: "You are a helpful..." }, error: null, retry_count: 0 },
      { id: "br-4", block_id: "block-llm", block_type: "llm", block_label: "Generate Response", status: "success", started_at: "2024-03-15T10:30:01Z", completed_at: "2024-03-15T10:30:03Z", duration_ms: 2100, input: {}, output: { response: "To reset your password..." }, error: null, retry_count: 0 },
      { id: "br-5", block_id: "block-output", block_type: "output", block_label: "Response", status: "success", started_at: "2024-03-15T10:30:03Z", completed_at: "2024-03-15T10:30:03Z", duration_ms: 3, input: {}, output: { response: "To reset your password..." }, error: null, retry_count: 0 },
    ],
  },
  {
    id: "run-2",
    workflow_id: "wf-1",
    workflow_name: "Customer Support Bot",
    status: "failed",
    started_at: "2024-03-15T10:25:00Z",
    completed_at: "2024-03-15T10:25:08Z",
    duration_ms: 8200,
    token_usage: { prompt_tokens: 320, completion_tokens: 0, total_tokens: 320 },
    input: { message: "Can you process a refund?" },
    output: null,
    error: "LLM API rate limit exceeded after 3 retries",
    block_runs: [
      { id: "br-6", block_id: "block-input", block_type: "input", block_label: "User Message", status: "success", started_at: "2024-03-15T10:25:00Z", completed_at: "2024-03-15T10:25:00Z", duration_ms: 4, input: {}, output: { message: "Can you process a refund?" }, error: null, retry_count: 0 },
      { id: "br-7", block_id: "block-kb", block_type: "knowledge_base", block_label: "Search Support Docs", status: "success", started_at: "2024-03-15T10:25:00Z", completed_at: "2024-03-15T10:25:01Z", duration_ms: 720, input: {}, output: { context: "Refund policy..." }, error: null, retry_count: 0 },
      { id: "br-8", block_id: "block-template", block_type: "template", block_label: "Build Prompt", status: "success", started_at: "2024-03-15T10:25:01Z", completed_at: "2024-03-15T10:25:01Z", duration_ms: 2, input: {}, output: {}, error: null, retry_count: 0 },
      { id: "br-9", block_id: "block-llm", block_type: "llm", block_label: "Generate Response", status: "failed", started_at: "2024-03-15T10:25:01Z", completed_at: "2024-03-15T10:25:08Z", duration_ms: 7000, input: {}, output: null, error: "Rate limit exceeded", retry_count: 3 },
    ],
  },
  {
    id: "run-3",
    workflow_id: "wf-2",
    workflow_name: "Blog Post Generator",
    status: "success",
    started_at: "2024-03-15T09:00:00Z",
    completed_at: "2024-03-15T09:00:25Z",
    duration_ms: 24500,
    token_usage: { prompt_tokens: 800, completion_tokens: 2200, total_tokens: 3000 },
    input: { topic: "AI in Healthcare", keywords: "machine learning, diagnostics, patient care", tone: "Professional" },
    output: { blog_post: "# AI in Healthcare: Transforming Patient Care..." },
    error: null,
    block_runs: [],
  },
];

export const mockMonitoringStats: MonitoringStats = {
  total_runs: 1247,
  success_count: 1189,
  failure_count: 58,
  avg_latency_ms: 3200,
  total_tokens: 2456000,
  runs_by_day: [
    { date: "2024-03-09", count: 145, success: 140, failure: 5 },
    { date: "2024-03-10", count: 167, success: 160, failure: 7 },
    { date: "2024-03-11", count: 189, success: 182, failure: 7 },
    { date: "2024-03-12", count: 201, success: 190, failure: 11 },
    { date: "2024-03-13", count: 178, success: 170, failure: 8 },
    { date: "2024-03-14", count: 195, success: 188, failure: 7 },
    { date: "2024-03-15", count: 172, success: 159, failure: 13 },
  ],
  latency_by_day: [
    { date: "2024-03-09", avg_ms: 2800 },
    { date: "2024-03-10", avg_ms: 3100 },
    { date: "2024-03-11", avg_ms: 2900 },
    { date: "2024-03-12", avg_ms: 3400 },
    { date: "2024-03-13", avg_ms: 3200 },
    { date: "2024-03-14", avg_ms: 3000 },
    { date: "2024-03-15", avg_ms: 3500 },
  ],
  tokens_by_day: [
    { date: "2024-03-09", tokens: 320000 },
    { date: "2024-03-10", tokens: 380000 },
    { date: "2024-03-11", tokens: 410000 },
    { date: "2024-03-12", tokens: 390000 },
    { date: "2024-03-13", tokens: 350000 },
    { date: "2024-03-14", tokens: 360000 },
    { date: "2024-03-15", tokens: 246000 },
  ],
  top_errors: [
    { message: "LLM API rate limit exceeded", count: 23 },
    { message: "Knowledge base query timeout", count: 12 },
    { message: "Invalid JSON in code block output", count: 8 },
    { message: "HTTP request timeout", count: 7 },
    { message: "Template variable not found", count: 5 },
  ],
};

export const mockMarketplaceItems: MarketplaceItem[] = [
  {
    id: "mp-1",
    workflow_id: "wf-mp-1",
    name: "Customer Support Agent",
    description: "Full-featured customer support chatbot with knowledge base integration.",
    long_description: "A production-ready customer support agent that uses RAG to provide accurate answers from your documentation. Includes fallback handling, escalation logic, and sentiment detection.",
    app_type: "chatbot",
    category: "Customer Support",
    tags: ["chatbot", "support", "rag", "knowledge-base"],
    author: { id: "user-100", name: "BuildStream Team", avatar_url: null },
    downloads: 2340,
    rating: 4.8,
    review_count: 156,
    preview_image_url: null,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
  },
  {
    id: "mp-2",
    workflow_id: "wf-mp-2",
    name: "SEO Blog Writer",
    description: "Generate SEO-optimized blog posts with keyword research integration.",
    long_description: "An automated blog writing workflow that performs keyword research, generates outlines, writes content, and optimizes for SEO. Supports multiple tones and languages.",
    app_type: "text_generator",
    category: "Content",
    tags: ["blog", "seo", "content", "writing"],
    author: { id: "user-101", name: "ContentPro", avatar_url: null },
    downloads: 1890,
    rating: 4.6,
    review_count: 89,
    preview_image_url: null,
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-02-28T10:00:00Z",
  },
  {
    id: "mp-3",
    workflow_id: "wf-mp-3",
    name: "Code Review Agent",
    description: "AI-powered code review agent that analyzes PRs and suggests improvements.",
    long_description: "An intelligent agent that reviews pull requests, identifies bugs, suggests improvements, checks for security vulnerabilities, and ensures code style consistency.",
    app_type: "agent",
    category: "Development",
    tags: ["code-review", "agent", "development", "security"],
    author: { id: "user-102", name: "DevTools Inc", avatar_url: null },
    downloads: 3120,
    rating: 4.9,
    review_count: 234,
    preview_image_url: null,
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-03-10T10:00:00Z",
  },
  {
    id: "mp-4",
    workflow_id: "wf-mp-4",
    name: "Data Extraction Pipeline",
    description: "Extract structured data from unstructured text documents.",
    long_description: "A workflow that processes unstructured documents, extracts key entities, relationships, and data points, then outputs structured JSON. Supports invoices, contracts, and reports.",
    app_type: "workflow",
    category: "Data Processing",
    tags: ["extraction", "data", "pipeline", "automation"],
    author: { id: "user-103", name: "DataFlow Labs", avatar_url: null },
    downloads: 1560,
    rating: 4.5,
    review_count: 67,
    preview_image_url: null,
    created_at: "2024-02-10T10:00:00Z",
    updated_at: "2024-03-05T10:00:00Z",
  },
  {
    id: "mp-5",
    workflow_id: "wf-mp-5",
    name: "Email Responder",
    description: "Automatically draft email responses based on context and tone.",
    long_description: "An intelligent email responder that reads incoming emails, understands context, determines appropriate tone, and drafts professional responses. Integrates with Gmail and Outlook.",
    app_type: "agent",
    category: "Productivity",
    tags: ["email", "automation", "productivity", "communication"],
    author: { id: "user-104", name: "AutoMail AI", avatar_url: null },
    downloads: 980,
    rating: 4.3,
    review_count: 45,
    preview_image_url: null,
    created_at: "2024-02-15T10:00:00Z",
    updated_at: "2024-03-08T10:00:00Z",
  },
  {
    id: "mp-6",
    workflow_id: "wf-mp-6",
    name: "Meeting Summarizer",
    description: "Transcribe and summarize meetings with action items extraction.",
    long_description: "Upload meeting recordings or transcripts and get structured summaries with key decisions, action items, and follow-ups. Supports multiple languages and export formats.",
    app_type: "workflow",
    category: "Productivity",
    tags: ["meetings", "summary", "transcription", "productivity"],
    author: { id: "user-105", name: "MeetingAI", avatar_url: null },
    downloads: 2100,
    rating: 4.7,
    review_count: 112,
    preview_image_url: null,
    created_at: "2024-02-20T10:00:00Z",
    updated_at: "2024-03-12T10:00:00Z",
  },
];
